-- ESTRUTURA DML

-- Criar banco de dados
CREATE DATABASE PRODUTO;

-- SELECIONAR O BANCO
USE PRODUTO;

-- CRIAR TABELA
CREATE TABLE PRODUTO(
    CODIGO INT,
    DESCRICAO VARCHAR(50),
    VALOR DOUBLE,
    DATA_CADASTRO DATE
);

-- ESTRUTURA DA TABELA
DESCRIBE PRODUTO;

-- INSERIR INFORMAÇÕES NO BANCO 
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, VALOR, DATA_CADASTRO) VALUES (1, "Camisa Preta", 39.90, "2020/05/07");

-- INSERINDO EM ORDEM DIFERENTE DA TABELA
INSERT INTO PRODUTOS (VALOR, CODIGO, DESCRICAO) VALUES (25.00, 2, "Boné Adidas");

-- INSERINDO SEM PASSAR NOME DAS TABELAS
INSERT INTO PRODUTOS VALUES (3, "Camisa Santos", 199.90, "2020/05/07");

-- ESSE COMANDO SÓ FUNCIONA NO MYSQL
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, VALOR, DATA_CADASTRO) VALUES
(4, "Camisa Verde", 39.90, "2020/05/07"),
(5, "Camisa Palmeiras", 108.00, "2020/05/07"),
(6, "Camisa Vasco", 150.90, "2020/05/07");

-- COMANDO PARA PESQUISA DE DADOS
SELECT * FROM PRODUTO;

-- SLECIONANDO DADOS EXPECIFICOS
SELECT DESCRICAO, VALOR FROM PRODUTO

--ATUALIZANDO DADOS
UPDATE PRODUTOS SET VALOR = 5.30 WHERE CODIGO = 1 

--  COM OPERADORES LOGICOS USANDO AND = ELE SÓ RETORNA VERDADEIRO
UPDATE PRODUTOS SET VALOR = 5.30 WHERE CODIGO = 1 AND DESCRICAO = 'Camisa Preta' AND VALOR = '39.90'; 

-- COM 2 AND
UPDATE PRODUTO SET DESCRICAO = 'NOVO NOME', DATA_CADASTRO = '2020/05/08', CODIGO = 1000 WHERE CODIGO = 7;

-- DELETANDO DADOS
DELETE FROM PRODUTOS WHERE CODIGO = 6 

-- OPERADORES ARITIMETICOS
SELECT 1 + 1 / 2

-- OPERADORES RELACIONAIS
SELECT * FROM PRODUTO WHERE CODIDO = 1;
SELECT * FROM PRODUTO WHERE CODIDO <= 1;
SELECT * FROM PRODUTO WHERE CODIDO < 1;
SELECT * FROM PRODUTO WHERE CODIDO >= 1;
SELECT * FROM PRODUTO WHERE CODIDO > 1;
SELECT * FROM PRODUTO WHERE CODIDO <> 1;
SELECT * FROM PRODUTO WHERE CODIDO != 1;

-- OPERADORES LOGICOS

-- E
SELECT * FROM PRODUTO WHERE CODIGO > 10 AND DESCRICAO = 'TESTE'

-- OU 
SELECT * FROM PRODUTO WHERE CODIGO > 10 OR DESCRICAO = 'TESTE'
SELECT * FROM PRODUTO WHERE ((CODIGO > 10 OR DESCRICAO = 'TESTE') AND CODIGO = 100) OR 1 = 1

-- OPERADORES DE CONJUNTO

-- COM O OR DO JEITO ANTIGO
SELECT * FROM PRODUTO WHERE CODIGO = 1 OR CODIGO = 5 OR CODIGO = 1000;

-- USANDO O IN PARA VALORES ESPECIFICOS
SELECT * FROM PRODUTO WHERE CODIGO IN(1,5,100);

-- USANDO NOT IN PARA FALAR OS QUAIS VC NÃO QUER
SELECT * FROM PRODUTO WHERE CODIGO NOT IN(1,5,100);

-- SELECIONANDO INTERVALOS
SELECT * FROM PRODUTO WHERE CODIGO BETWENN 1 AND 1000;
SELECT * FROM PRODUTO WHERE CODIGO NOT BETWENN 1 AND 1000;

-- NULL TODOS DADADOS VAZIOS
SELECT * FROM PRODUTO WHERE DATA_CADASTRO IN NULL;

-- NOT NULL DADOS PREENCHIDOS
SELECT * FROM PRODUTO WHERE DATA_CADASTRO IN NOT NULL;

-- LIKE PARA FAZER PESQUISA
SELECT * FROM PRODUTO WHERE DESCRICAO LIKE "CANETA"

-- COMEÇO DO NOME
SELECT * FROM PRODUTO WHERE DESCRICAO LIKE "CA%"

-- FIM DO NOME
SELECT * FROM PRODUTO WHERE DESCRICAO LIKE "%A"

-- TODO TEXTO
SELECT * FROM PRODUTO WHERE DESCRICAO LIKE "%A%"
