-- ESTRUTURA DML

-- Criar banco de dados
CREATE DATABASE PRODUTO;

-- SELECIONAR O BANCO
USE PRODUTO;

-- CRIAR TABELA
CREATE TABLE PRODUTO(
    CODIGO INT,
    DESCRICAO VARCHAR(50),
    VALOR DOUBLE,
    DATA_CADASTRO DATE
);

-- ESTRUTURA DA TABELA
DESCRIBE PRODUTO;

-- INSERIR INFORMAÇÕES NO BANCO 
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, VALOR, DATA_CADASTRO) VALUES (1, "Camisa Preta", 39.90, "2020/05/07");

-- INSERINDO EM ORDEM DIFERENTE DA TABELA
INSERT INTO PRODUTOS (VALOR, CODIGO, DESCRICAO) VALUES (25.00, 2, "Boné Adidas");

-- INSERINDO SEM PASSAR NOME DAS TABELAS
INSERT INTO PRODUTOS VALUES (3, "Camisa Santos", 199.90, "2020/05/07");

-- ESSE COMANDO SÓ FUNCIONA NO MYSQL
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, VALOR, DATA_CADASTRO) VALUES
(4, "Camisa Verde", 39.90, "2020/05/07"),
(5, "Camisa Palmeiras", 108.00, "2020/05/07"),
(6, "Camisa Vasco", 150.90, "2020/05/07");

-- COMANDO PARA PESQUISA DE DADOS
SELECT * FROM PRODUTO;

-- SLECIONANDO DADOS EXPECIFICOS
SELECT DESCRICAO, VALOR FROM PRODUTO

--ATUALIZANDO DADOS
UPDATE PRODUTOS SET VALOR = 5.30 WHERE CODIGO = 1 

--  COM OPERADORES LOGICOS USANDO AND = ELE SÓ RETORNA VERDADEIRO
UPDATE PRODUTOS SET VALOR = 5.30 WHERE CODIGO = 1 AND DESCRICAO = 'Camisa Preta' AND VALOR = '39.90'; 

-- COM 2 AND
UPDATE PRODUTO SET DESCRICAO = 'NOVO NOME', DATA_CADASTRO = '2020/05/08', CODIGO = 1000 WHERE CODIGO = 7;

-- DELETANDO DADOS
DELETE FROM PRODUTOS WHERE CODIGO = 6 